[metadata]
name = dsa-csv-plugin
version = 0.1.0

[options]
packages = dsa_csv_plugin
install_requires =
    girder>=3.0.0

[options.entry_points]
girder.plugin =
    dsa_csv = dsa_csv_plugin:DsaCsvPlugin

[options.package_data]
dsa_csv_plugin =
    web_client/package.json
    web_client/*.js
    web_client/views/*.js
